"""
Object bank for Seekr.
Each entry has:
  displayName  - shown to players
  prompts      - positive CLIP descriptions
  negatives    - things to distinguish from (combined with GLOBAL_NULLS)
  threshold    - min positive similarity to count as detected
  margin       - min gap between positive and negative score
"""

# _ALL_OBJECTS: dict = {
#     # ── HARDCODED TEST: sunglasses, backpack, thermos, pencil, cushion, water_bottle ──
#     "sunglasses": { ... },
#     "backpack": { ... },
#     "thermos": { ... },
#     "pencil": { ... },
#     "cushion": { ... },
#     "water_bottle": { ... },
# }

# Fixed spawn order for test
_TEST_ORDER = ["pen", "backpack", "sunglasses", "water_bottle"]

ORIGINAL_OBJECTS: dict = {
    "water_bottle": {
        "displayName": "WATER BOTTLE",
        "prompts": [
            "a water bottle",
            "a plastic water bottle",
            "a reusable water bottle",
            "someone holding a water bottle",
        ],
        "negatives": ["a coffee mug", "a glass", "a vase", "a phone", "a spoon"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    "phone": {
        "displayName": "SMARTPHONE",
        "prompts": [
            "a smartphone",
            "a mobile phone",
            "someone holding a phone",
            "a phone with a screen",
        ],
        "negatives": ["a tablet", "a remote control", "a calculator", "a water bottle", "a keyboard"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    "notebook": {
        "displayName": "NOTEBOOK",
        "prompts": [
            "a spiral notebook",
            "someone holding a notebook",
            "a lined writing notebook",
            "a notebook on a desk",
        ],
        "negatives": ["a book", "a tablet", "a sketchbook", "a magazine", "a keyboard"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    "keyboard": {
        "displayName": "KEYBOARD",
        "prompts": [
            "a computer keyboard",
            "a mechanical keyboard",
            "a USB keyboard",
            "someone holding a keyboard",
            "a keyboard on a desk",
        ],
        "negatives": ["a remote control", "a piano", "a calculator", "a phone", "a laptop"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    "charger": {
        "displayName": "PHONE CHARGER",
        "prompts": [
            "a phone charger cable",
            "a USB charging cable",
            "someone holding a charger",
            "a power cable",
        ],
        "negatives": ["earphones", "a wire", "a rope", "a belt"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    "spoon": {
        "displayName": "SPOON",
        "prompts": [
            "a spoon",
            "a metal spoon",
            "someone holding a spoon",
            "a spoon on a table",
        ],
        "negatives": ["a fork", "a knife", "chopsticks", "a ladle", "a water bottle"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    # ── Kitchen & dining ────────────────────────────────────────────
    "coffee_mug": {
        "displayName": "COFFEE MUG",
        "prompts": [
            "a coffee mug",
            "a ceramic mug",
            "someone holding a coffee mug",
            "a mug with a handle",
        ],
        "negatives": ["a glass", "a water bottle", "a bowl", "a vase", "a jar"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    "fork": {
        "displayName": "FORK",
        "prompts": [
            "a fork",
            "a metal fork",
            "someone holding a fork",
            "a dining fork",
        ],
        "negatives": ["a spoon", "a knife", "chopsticks", "a pen", "a comb"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    "knife": {
        "displayName": "BUTTER KNIFE",
        "prompts": [
            "a butter knife",
            "a table knife",
            "someone holding a butter knife",
            "a dining knife",
        ],
        "negatives": ["a fork", "a spoon", "a ruler", "a pen", "scissors"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    "plate": {
        "displayName": "PLATE",
        "prompts": [
            "a dinner plate",
            "a ceramic plate",
            "someone holding a plate",
            "a white plate",
        ],
        "negatives": ["a bowl", "a cutting board", "a lid", "a frisbee", "a tray"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    "bowl": {
        "displayName": "BOWL",
        "prompts": [
            "a bowl",
            "a cereal bowl",
            "someone holding a bowl",
            "a ceramic bowl on a table",
        ],
        "negatives": ["a plate", "a mug", "a cup", "a pot", "a hat"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    "drinking_glass": {
        "displayName": "DRINKING GLASS",
        "prompts": [
            "a drinking glass",
            "a clear glass cup",
            "someone holding a glass",
            "a glass of water",
        ],
        "negatives": ["a mug", "a water bottle", "a jar", "a vase", "a phone"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    "frying_pan": {
        "displayName": "FRYING PAN",
        "prompts": [
            "a frying pan",
            "a skillet",
            "someone holding a frying pan",
            "a non-stick pan",
        ],
        "negatives": ["a pot", "a plate", "a lid", "a cutting board", "a tray"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    "spatula": {
        "displayName": "SPATULA",
        "prompts": [
            "a spatula",
            "a cooking spatula",
            "someone holding a spatula",
            "a kitchen spatula",
        ],
        "negatives": ["a spoon", "a fork", "a knife", "a ruler", "a brush"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    "cutting_board": {
        "displayName": "CUTTING BOARD",
        "prompts": [
            "a cutting board",
            "a wooden cutting board",
            "someone holding a cutting board",
            "a chopping board",
        ],
        "negatives": ["a plate", "a tray", "a book", "a tablet", "a clipboard"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    "paper_towel": {
        "displayName": "PAPER TOWEL ROLL",
        "prompts": [
            "a paper towel roll",
            "a roll of paper towels",
            "someone holding a paper towel roll",
            "a kitchen paper roll",
        ],
        "negatives": ["a toilet paper roll", "a water bottle", "a can", "a tube", "a rolling pin"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    "banana": {
        "displayName": "BANANA",
        "prompts": [
            "a banana",
            "a yellow banana",
            "someone holding a banana",
            "a banana on a table",
        ],
        "negatives": ["a phone", "a remote control", "a cucumber", "a zucchini", "a pen"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    "apple": {
        "displayName": "APPLE",
        "prompts": [
            "an apple",
            "a red apple",
            "someone holding an apple",
            "a green apple",
        ],
        "negatives": ["an orange", "a ball", "a tomato", "a peach", "a mug"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    "orange": {
        "displayName": "ORANGE",
        "prompts": [
            "an orange fruit",
            "an orange",
            "someone holding an orange",
            "a citrus orange",
        ],
        "negatives": ["an apple", "a ball", "a grapefruit", "a tomato", "a mug"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    "bread": {
        "displayName": "BREAD",
        "prompts": [
            "a loaf of bread",
            "sliced bread",
            "someone holding bread",
            "a bread loaf",
        ],
        "negatives": ["a cutting board", "a pillow", "a sponge", "a book", "a towel"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    "cereal_box": {
        "displayName": "CEREAL BOX",
        "prompts": [
            "a cereal box",
            "a box of cereal",
            "someone holding a cereal box",
            "a breakfast cereal box",
        ],
        "negatives": ["a book", "a tissue box", "a shoebox", "a package", "a tablet"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    "can": {
        "displayName": "CANNED FOOD",
        "prompts": [
            "a can of food",
            "a tin can",
            "someone holding a can",
            "a canned good",
        ],
        "negatives": ["a mug", "a water bottle", "a jar", "a glass", "a cup"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    "tupperware": {
        "displayName": "FOOD CONTAINER",
        "prompts": [
            "a plastic food container",
            "a tupperware container",
            "someone holding a food container",
            "a storage container with a lid",
        ],
        "negatives": ["a bowl", "a plate", "a box", "a lunchbox", "a tray"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    "oven_mitt": {
        "displayName": "OVEN MITT",
        "prompts": [
            "an oven mitt",
            "a kitchen oven glove",
            "someone holding an oven mitt",
            "a heat-resistant kitchen glove",
        ],
        "negatives": ["a glove", "a sock", "a towel", "a hat", "a slipper"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    "whisk": {
        "displayName": "WHISK",
        "prompts": [
            "a whisk",
            "a kitchen whisk",
            "someone holding a whisk",
            "a wire whisk",
        ],
        "negatives": ["a spoon", "a fork", "a spatula", "a brush", "a pen"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    "pot": {
        "displayName": "COOKING POT",
        "prompts": [
            "a cooking pot",
            "a saucepan",
            "someone holding a pot",
            "a metal cooking pot",
        ],
        "negatives": ["a frying pan", "a bowl", "a mug", "a bucket", "a helmet"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    "tongs": {
        "displayName": "TONGS",
        "prompts": [
            "kitchen tongs",
            "a pair of tongs",
            "someone holding tongs",
            "cooking tongs",
        ],
        "negatives": ["scissors", "pliers", "a fork", "a spatula", "chopsticks"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    "mug_coaster": {
        "displayName": "COASTER",
        "prompts": [
            "a coaster",
            "a drink coaster",
            "a coaster on a table",
            "someone holding a coaster",
        ],
        "negatives": ["a plate", "a lid", "a coin", "a mouse pad", "a sticky note"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    # ── Personal items & accessories ────────────────────────────────
    "sunglasses": {
        "displayName": "SUNGLASSES",
        "prompts": [
            "a pair of sunglasses",
            "sunglasses",
            "someone holding sunglasses",
            "dark tinted glasses",
        ],
        "negatives": ["reading glasses", "goggles", "a phone", "a headband", "a watch"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    "eyeglasses": {
        "displayName": "EYEGLASSES",
        "prompts": [
            "a pair of eyeglasses",
            "reading glasses",
            "someone holding glasses",
            "prescription eyeglasses",
        ],
        "negatives": ["sunglasses", "goggles", "a magnifying glass", "a phone", "a headband"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    "wallet": {
        "displayName": "WALLET",
        "prompts": [
            "a wallet",
            "a leather wallet",
            "someone holding a wallet",
            "an open wallet",
        ],
        "negatives": ["a phone", "a book", "a notebook", "a passport", "a card"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    "keys": {
        "displayName": "KEYS",
        "prompts": [
            "a set of keys",
            "house keys",
            "someone holding keys",
            "keys on a keychain",
        ],
        "negatives": ["a coin", "a pen", "a lighter", "a USB drive", "a phone"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    "wristwatch": {
        "displayName": "WRISTWATCH",
        "prompts": [
            "a wristwatch",
            "a watch",
            "someone holding a wristwatch",
            "a watch on a wrist",
        ],
        "negatives": ["a bracelet", "a phone", "a compass", "a rubber band", "a ring"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    "baseball_cap": {
        "displayName": "CAP / HAT",
        "prompts": [
            "a baseball cap",
            "a hat",
            "someone holding a cap",
            "a baseball hat",
        ],
        "negatives": ["a bowl", "a helmet", "a frisbee", "a plate", "headphones"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    "shoe": {
        "displayName": "SHOE",
        "prompts": [
            "a shoe",
            "a sneaker",
            "someone holding a shoe",
            "a running shoe",
        ],
        "negatives": ["a slipper", "a sandal", "a boot", "a sock", "a glove"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    "sock": {
        "displayName": "SOCK",
        "prompts": [
            "a sock",
            "a pair of socks",
            "someone holding a sock",
            "a cotton sock",
        ],
        "negatives": ["a glove", "a shoe", "a slipper", "a sleeve", "a hat"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    "belt": {
        "displayName": "BELT",
        "prompts": [
            "a belt",
            "a leather belt",
            "someone holding a belt",
            "a belt with a buckle",
        ],
        "negatives": ["a rope", "a charger cable", "headphones", "a strap", "a leash"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    "backpack": {
        "displayName": "BACKPACK",
        "prompts": [
            "a backpack",
            "a school backpack",
            "someone holding a backpack",
            "a backpack with straps",
        ],
        "negatives": ["a handbag", "a suitcase", "a pillow", "a jacket", "a sleeping bag"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    "umbrella": {
        "displayName": "UMBRELLA",
        "prompts": [
            "an umbrella",
            "a closed umbrella",
            "someone holding an umbrella",
            "a folded umbrella",
        ],
        "negatives": ["a cane", "a bat", "a stick", "a broom", "a golf club"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    "hairbrush": {
        "displayName": "HAIRBRUSH",
        "prompts": [
            "a hairbrush",
            "a hair brush",
            "someone holding a hairbrush",
            "a paddle brush",
        ],
        "negatives": ["a comb", "a toothbrush", "a remote control", "a spatula", "a microphone"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    "slipper": {
        "displayName": "SLIPPER",
        "prompts": [
            "a slipper",
            "a house slipper",
            "someone holding a slipper",
            "a fluffy slipper",
        ],
        "negatives": ["a shoe", "a sock", "a sandal", "a glove", "a boot"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    "hoodie": {
        "displayName": "HOODIE",
        "prompts": [
            "a hoodie",
            "a hooded sweatshirt",
            "someone holding a hoodie",
            "a zip-up hoodie",
        ],
        "negatives": ["a jacket", "a t-shirt", "a blanket", "a towel", "a backpack"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    "t_shirt": {
        "displayName": "T-SHIRT",
        "prompts": [
            "a t-shirt",
            "a folded t-shirt",
            "someone holding a t-shirt",
            "a cotton t-shirt",
        ],
        "negatives": ["a hoodie", "a jacket", "a towel", "a blanket", "a pillowcase"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    "scarf": {
        "displayName": "SCARF",
        "prompts": [
            "a scarf",
            "a winter scarf",
            "someone holding a scarf",
            "a knitted scarf",
        ],
        "negatives": ["a towel", "a belt", "a tie", "a blanket", "a rope"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    # ── Electronics ─────────────────────────────────────────────────
    "headphones": {
        "displayName": "HEADPHONES",
        "prompts": [
            "a pair of headphones",
            "over-ear headphones",
            "someone holding headphones",
            "wireless headphones",
        ],
        "negatives": ["earbuds", "a headband", "a hat", "a stethoscope", "earmuffs"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    "earbuds": {
        "displayName": "EARBUDS",
        "prompts": [
            "earbuds",
            "wireless earbuds",
            "someone holding earbuds",
            "earbuds in a charging case",
        ],
        "negatives": ["headphones", "a hearing aid", "a USB drive", "a coin", "a pill"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    "remote_control": {
        "displayName": "REMOTE CONTROL",
        "prompts": [
            "a remote control",
            "a TV remote",
            "someone holding a remote control",
            "a remote with buttons",
        ],
        "negatives": ["a phone", "a calculator", "a keyboard", "a game controller", "a mouse"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    "laptop": {
        "displayName": "LAPTOP",
        "prompts": [
            "a laptop computer",
            "an open laptop",
            "a laptop on a desk",
            "someone using a laptop",
        ],
        "negatives": ["a tablet", "a keyboard", "a book", "a monitor", "a phone"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    "tablet": {
        "displayName": "TABLET",
        "prompts": [
            "a tablet device",
            "an iPad",
            "someone holding a tablet",
            "a tablet computer",
        ],
        "negatives": ["a phone", "a laptop", "a book", "a clipboard", "a cutting board"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    "computer_mouse": {
        "displayName": "COMPUTER MOUSE",
        "prompts": [
            "a computer mouse",
            "a wireless mouse",
            "someone holding a computer mouse",
            "a mouse on a mouse pad",
        ],
        "negatives": ["a remote control", "a phone", "a soap bar", "a stapler", "a rock"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    "usb_drive": {
        "displayName": "USB FLASH DRIVE",
        "prompts": [
            "a USB flash drive",
            "a thumb drive",
            "someone holding a USB drive",
            "a USB stick",
        ],
        "negatives": ["a lighter", "a pen cap", "a battery", "a key", "a lipstick"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    "power_bank": {
        "displayName": "POWER BANK",
        "prompts": [
            "a power bank",
            "a portable charger",
            "someone holding a power bank",
            "a battery pack",
        ],
        "negatives": ["a phone", "a remote control", "a wallet", "a hard drive", "a chocolate bar"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    "bluetooth_speaker": {
        "displayName": "BLUETOOTH SPEAKER",
        "prompts": [
            "a bluetooth speaker",
            "a portable speaker",
            "someone holding a speaker",
            "a wireless speaker",
        ],
        "negatives": ["a water bottle", "a can", "a mug", "a flashlight", "a thermos"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    "game_controller": {
        "displayName": "GAME CONTROLLER",
        "prompts": [
            "a game controller",
            "a video game controller",
            "someone holding a game controller",
            "a gamepad",
        ],
        "negatives": ["a remote control", "a phone", "a mouse", "a calculator", "a walkie-talkie"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    "extension_cord": {
        "displayName": "EXTENSION CORD",
        "prompts": [
            "an extension cord",
            "a power strip",
            "someone holding an extension cord",
            "a surge protector",
        ],
        "negatives": ["a charger cable", "a rope", "a hose", "a belt", "headphones"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    # ── Bathroom items ──────────────────────────────────────────────
    "toothbrush": {
        "displayName": "TOOTHBRUSH",
        "prompts": [
            "a toothbrush",
            "someone holding a toothbrush",
            "a manual toothbrush",
            "a toothbrush with bristles",
        ],
        "negatives": ["a pen", "a hairbrush", "a comb", "a marker", "a spatula"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    "towel": {
        "displayName": "TOWEL",
        "prompts": [
            "a towel",
            "a bath towel",
            "someone holding a towel",
            "a folded towel",
        ],
        "negatives": ["a blanket", "a t-shirt", "a scarf", "a pillowcase", "a rag"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    "soap_bar": {
        "displayName": "BAR OF SOAP",
        "prompts": [
            "a bar of soap",
            "a soap bar",
            "someone holding a bar of soap",
            "a hand soap bar",
        ],
        "negatives": ["a sponge", "an eraser", "a phone", "a block", "a rock"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    "shampoo_bottle": {
        "displayName": "SHAMPOO BOTTLE",
        "prompts": [
            "a shampoo bottle",
            "a bottle of shampoo",
            "someone holding a shampoo bottle",
            "a hair product bottle",
        ],
        "negatives": ["a water bottle", "a lotion bottle", "a soap dispenser", "a spray bottle", "a detergent bottle"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    "tissue_box": {
        "displayName": "TISSUE BOX",
        "prompts": [
            "a tissue box",
            "a box of tissues",
            "someone holding a tissue box",
            "a facial tissue box",
        ],
        "negatives": ["a cereal box", "a shoebox", "a package", "a book", "a block"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    "toilet_paper": {
        "displayName": "TOILET PAPER ROLL",
        "prompts": [
            "a toilet paper roll",
            "a roll of toilet paper",
            "someone holding toilet paper",
            "a bathroom tissue roll",
        ],
        "negatives": ["a paper towel roll", "a tape roll", "a can", "a mug", "a water bottle"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    "hand_sanitizer": {
        "displayName": "HAND SANITIZER",
        "prompts": [
            "a hand sanitizer bottle",
            "hand sanitizer",
            "someone holding hand sanitizer",
            "a pump bottle of sanitizer",
        ],
        "negatives": ["a soap dispenser", "a water bottle", "a lotion bottle", "a shampoo bottle", "a spray bottle"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    "lotion_bottle": {
        "displayName": "LOTION BOTTLE",
        "prompts": [
            "a lotion bottle",
            "a bottle of lotion",
            "someone holding a lotion bottle",
            "a moisturizer bottle",
        ],
        "negatives": ["a shampoo bottle", "a water bottle", "a soap dispenser", "a hand sanitizer", "a spray bottle"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    # ── Office & desk items ─────────────────────────────────────────
    "pen": {
        "displayName": "PEN",
        "prompts": [
            "a pen",
            "a ballpoint pen",
            "someone holding a pen",
            "a writing pen",
        ],
        "negatives": ["a pencil", "a marker", "a stylus", "chopsticks", "a toothbrush"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    "pencil": {
        "displayName": "PENCIL",
        "prompts": [
            "a pencil",
            "a wooden pencil",
            "someone holding a pencil",
            "a yellow pencil",
        ],
        "negatives": ["a pen", "a marker", "a chopstick", "a straw", "a stick"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    "scissors": {
        "displayName": "SCISSORS",
        "prompts": [
            "a pair of scissors",
            "scissors",
            "someone holding scissors",
            "craft scissors",
        ],
        "negatives": ["pliers", "tongs", "a knife", "tweezers", "a can opener"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    "stapler": {
        "displayName": "STAPLER",
        "prompts": [
            "a stapler",
            "a desk stapler",
            "someone holding a stapler",
            "an office stapler",
        ],
        "negatives": ["a hole punch", "a tape dispenser", "a mouse", "a phone", "a remote"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    "tape_dispenser": {
        "displayName": "TAPE DISPENSER",
        "prompts": [
            "a tape dispenser",
            "a roll of tape",
            "someone holding a tape dispenser",
            "a scotch tape dispenser",
        ],
        "negatives": ["a stapler", "a mouse", "a can", "a clock", "a snail"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    "sticky_note": {
        "displayName": "STICKY NOTE",
        "prompts": [
            "a sticky note",
            "a post-it note",
            "someone holding a sticky note",
            "a yellow sticky note",
        ],
        "negatives": ["a piece of paper", "an envelope", "a card", "a coaster", "a napkin"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    "eraser": {
        "displayName": "ERASER",
        "prompts": [
            "an eraser",
            "a rubber eraser",
            "someone holding an eraser",
            "a pink eraser",
        ],
        "negatives": ["a soap bar", "a block", "a USB drive", "a lipstick", "a battery"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    "ruler": {
        "displayName": "RULER",
        "prompts": [
            "a ruler",
            "a straight ruler",
            "someone holding a ruler",
            "a measuring ruler",
        ],
        "negatives": ["a knife", "a pen", "a stick", "a spatula", "a remote control"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    "envelope": {
        "displayName": "ENVELOPE",
        "prompts": [
            "an envelope",
            "a mail envelope",
            "someone holding an envelope",
            "a white envelope",
        ],
        "negatives": ["a piece of paper", "a sticky note", "a napkin", "a card", "a folder"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    "book": {
        "displayName": "BOOK",
        "prompts": [
            "a book",
            "a hardcover book",
            "someone holding a book",
            "a book on a table",
        ],
        "negatives": ["a notebook", "a magazine", "a tablet", "a laptop", "a clipboard"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    "marker": {
        "displayName": "MARKER",
        "prompts": [
            "a marker",
            "a felt-tip marker",
            "someone holding a marker",
            "a dry erase marker",
        ],
        "negatives": ["a pen", "a pencil", "a highlighter", "a lipstick", "a battery"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    "clipboard": {
        "displayName": "CLIPBOARD",
        "prompts": [
            "a clipboard",
            "a clipboard with paper",
            "someone holding a clipboard",
            "an office clipboard",
        ],
        "negatives": ["a tablet", "a book", "a cutting board", "a tray", "a notebook"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    "calculator": {
        "displayName": "CALCULATOR",
        "prompts": [
            "a calculator",
            "a desk calculator",
            "someone holding a calculator",
            "a scientific calculator",
        ],
        "negatives": ["a phone", "a remote control", "a game controller", "a keyboard", "a tablet"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    "rubber_band": {
        "displayName": "RUBBER BAND",
        "prompts": [
            "a rubber band",
            "rubber bands",
            "someone holding a rubber band",
            "a stretched rubber band",
        ],
        "negatives": ["a hair tie", "a ring", "a bracelet", "a string", "a wire"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    # ── Living room & decor ─────────────────────────────────────────
    "pillow": {
        "displayName": "PILLOW",
        "prompts": [
            "a pillow",
            "a throw pillow",
            "someone holding a pillow",
            "a couch pillow",
        ],
        "negatives": ["a cushion", "a blanket", "a towel", "a bag", "a stuffed animal"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    "blanket": {
        "displayName": "BLANKET",
        "prompts": [
            "a blanket",
            "a folded blanket",
            "someone holding a blanket",
            "a throw blanket",
        ],
        "negatives": ["a towel", "a pillow", "a jacket", "a curtain", "a rug"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    "candle": {
        "displayName": "CANDLE",
        "prompts": [
            "a candle",
            "a jar candle",
            "someone holding a candle",
            "a scented candle",
        ],
        "negatives": ["a glass", "a jar", "a mug", "a vase", "a water bottle"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    "potted_plant": {
        "displayName": "POTTED PLANT",
        "prompts": [
            "a potted plant",
            "a houseplant",
            "a small potted plant",
            "a plant in a pot",
        ],
        "negatives": ["a vase with flowers", "a mug", "a bowl", "a can", "a bouquet"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    "picture_frame": {
        "displayName": "PICTURE FRAME",
        "prompts": [
            "a picture frame",
            "a photo frame",
            "someone holding a picture frame",
            "a framed photo",
        ],
        "negatives": ["a mirror", "a tablet", "a painting", "a book", "a clipboard"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    "clock": {
        "displayName": "CLOCK",
        "prompts": [
            "a clock",
            "a wall clock",
            "an alarm clock",
            "someone holding a clock",
        ],
        "negatives": ["a watch", "a plate", "a mirror", "a compass", "a phone"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    "lamp": {
        "displayName": "DESK LAMP",
        "prompts": [
            "a desk lamp",
            "a table lamp",
            "a lamp on a desk",
            "someone pointing at a lamp",
        ],
        "negatives": ["a flashlight", "a candle", "a microphone", "a speaker", "a vase"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    "vase": {
        "displayName": "VASE",
        "prompts": [
            "a vase",
            "a flower vase",
            "someone holding a vase",
            "a decorative vase",
        ],
        "negatives": ["a water bottle", "a glass", "a jar", "a mug", "a can"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    "stuffed_animal": {
        "displayName": "STUFFED ANIMAL",
        "prompts": [
            "a stuffed animal",
            "a plush toy",
            "someone holding a stuffed animal",
            "a teddy bear",
        ],
        "negatives": ["a pillow", "a doll", "a sock", "a hat", "a blanket"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    "cushion": {
        "displayName": "COUCH CUSHION",
        "prompts": [
            "a couch cushion",
            "a seat cushion",
            "someone holding a cushion",
            "a sofa cushion",
        ],
        "negatives": ["a pillow", "a blanket", "a towel", "a bag", "a mat"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    # ── Cleaning & laundry ──────────────────────────────────────────
    "broom": {
        "displayName": "BROOM",
        "prompts": [
            "a broom",
            "a household broom",
            "someone holding a broom",
            "a broom leaning against a wall",
        ],
        "negatives": ["a mop", "an umbrella", "a cane", "a bat", "a stick"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    "sponge": {
        "displayName": "SPONGE",
        "prompts": [
            "a sponge",
            "a kitchen sponge",
            "someone holding a sponge",
            "a cleaning sponge",
        ],
        "negatives": ["a soap bar", "an eraser", "a block", "a phone", "a wallet"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    "spray_bottle": {
        "displayName": "SPRAY BOTTLE",
        "prompts": [
            "a spray bottle",
            "a cleaning spray bottle",
            "someone holding a spray bottle",
            "a trigger spray bottle",
        ],
        "negatives": ["a water bottle", "a shampoo bottle", "a lotion bottle", "a hand sanitizer", "a detergent bottle"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    "laundry_basket": {
        "displayName": "LAUNDRY BASKET",
        "prompts": [
            "a laundry basket",
            "a laundry hamper",
            "someone holding a laundry basket",
            "a clothes basket",
        ],
        "negatives": ["a trash can", "a bucket", "a box", "a bag", "a bin"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    "trash_bag": {
        "displayName": "TRASH BAG",
        "prompts": [
            "a trash bag",
            "a garbage bag",
            "someone holding a trash bag",
            "a black plastic bag",
        ],
        "negatives": ["a backpack", "a shopping bag", "a suitcase", "a pillow", "a blanket"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    "dustpan": {
        "displayName": "DUSTPAN",
        "prompts": [
            "a dustpan",
            "a dustpan and brush",
            "someone holding a dustpan",
            "a hand dustpan",
        ],
        "negatives": ["a tray", "a plate", "a cutting board", "a clipboard", "a fan"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    # ── Miscellaneous household ─────────────────────────────────────
    "playing_cards": {
        "displayName": "PLAYING CARDS",
        "prompts": [
            "playing cards",
            "a deck of cards",
            "someone holding playing cards",
            "a hand of cards",
        ],
        "negatives": ["a phone", "a wallet", "sticky notes", "a notebook", "an envelope"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    "dice": {
        "displayName": "DICE",
        "prompts": [
            "dice",
            "a pair of dice",
            "someone holding dice",
            "a six-sided die",
        ],
        "negatives": ["a block", "a sugar cube", "a bead", "an eraser", "a button"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    "lighter": {
        "displayName": "LIGHTER",
        "prompts": [
            "a lighter",
            "a pocket lighter",
            "someone holding a lighter",
            "a BIC lighter",
        ],
        "negatives": ["a USB drive", "a lipstick", "a battery", "a pen cap", "a whistle"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    "flashlight": {
        "displayName": "FLASHLIGHT",
        "prompts": [
            "a flashlight",
            "a torch",
            "someone holding a flashlight",
            "a handheld flashlight",
        ],
        "negatives": ["a water bottle", "a microphone", "a remote control", "a speaker", "a can"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    "screwdriver": {
        "displayName": "SCREWDRIVER",
        "prompts": [
            "a screwdriver",
            "a Phillips screwdriver",
            "someone holding a screwdriver",
            "a flathead screwdriver",
        ],
        "negatives": ["a pen", "a knife", "a chopstick", "a thermometer", "a pencil"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    "tape_measure": {
        "displayName": "TAPE MEASURE",
        "prompts": [
            "a tape measure",
            "a measuring tape",
            "someone holding a tape measure",
            "a retractable tape measure",
        ],
        "negatives": ["a ruler", "a compass", "a watch", "a yo-yo", "a padlock"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    "shopping_bag": {
        "displayName": "SHOPPING BAG",
        "prompts": [
            "a shopping bag",
            "a reusable shopping bag",
            "someone holding a shopping bag",
            "a tote bag",
        ],
        "negatives": ["a backpack", "a trash bag", "a purse", "a suitcase", "a pillowcase"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    "battery": {
        "displayName": "BATTERY",
        "prompts": [
            "a battery",
            "an AA battery",
            "someone holding a battery",
            "a double-A battery",
        ],
        "negatives": ["a lighter", "a USB drive", "a lipstick", "a marker cap", "a bullet"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    "jar": {
        "displayName": "JAR",
        "prompts": [
            "a glass jar",
            "a mason jar",
            "someone holding a jar",
            "a jar with a lid",
        ],
        "negatives": ["a glass", "a mug", "a can", "a vase", "a water bottle"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    "handbag": {
        "displayName": "HANDBAG / PURSE",
        "prompts": [
            "a handbag",
            "a purse",
            "someone holding a handbag",
            "a shoulder bag",
        ],
        "negatives": ["a backpack", "a shopping bag", "a wallet", "a lunchbox", "a suitcase"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    "magazine": {
        "displayName": "MAGAZINE",
        "prompts": [
            "a magazine",
            "someone holding a magazine",
            "a glossy magazine",
            "a magazine on a table",
        ],
        "negatives": ["a book", "a notebook", "a newspaper", "a tablet", "a folder"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    "comb": {
        "displayName": "COMB",
        "prompts": [
            "a comb",
            "a hair comb",
            "someone holding a comb",
            "a plastic comb",
        ],
        "negatives": ["a hairbrush", "a fork", "a toothbrush", "a ruler", "a pen"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    "nail_clipper": {
        "displayName": "NAIL CLIPPER",
        "prompts": [
            "a nail clipper",
            "nail clippers",
            "someone holding a nail clipper",
            "a fingernail clipper",
        ],
        "negatives": ["a stapler", "scissors", "a lighter", "a USB drive", "a paper clip"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    "water_jug": {
        "displayName": "WATER JUG / PITCHER",
        "prompts": [
            "a water jug",
            "a pitcher",
            "someone holding a water pitcher",
            "a water filter pitcher",
        ],
        "negatives": ["a water bottle", "a kettle", "a vase", "a mug", "a watering can"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    "kettle": {
        "displayName": "KETTLE",
        "prompts": [
            "a kettle",
            "an electric kettle",
            "someone holding a kettle",
            "a tea kettle",
        ],
        "negatives": ["a pot", "a water jug", "a coffee maker", "a vase", "a thermos"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    "plastic_bag": {
        "displayName": "PLASTIC BAG",
        "prompts": [
            "a plastic bag",
            "a grocery bag",
            "someone holding a plastic bag",
            "a white plastic bag",
        ],
        "negatives": ["a shopping bag", "a trash bag", "a paper bag", "a backpack", "a towel"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    "chopsticks": {
        "displayName": "CHOPSTICKS",
        "prompts": [
            "chopsticks",
            "a pair of chopsticks",
            "someone holding chopsticks",
            "wooden chopsticks",
        ],
        "negatives": ["a pencil", "a pen", "a straw", "a stick", "a knitting needle"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    "straw": {
        "displayName": "DRINKING STRAW",
        "prompts": [
            "a drinking straw",
            "a reusable straw",
            "someone holding a straw",
            "a metal straw",
        ],
        "negatives": ["a pen", "a chopstick", "a pencil", "a stick", "a stirrer"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    "lunch_box": {
        "displayName": "LUNCH BOX",
        "prompts": [
            "a lunch box",
            "a lunchbox",
            "someone holding a lunch box",
            "a packed lunch container",
        ],
        "negatives": ["a food container", "a toolbox", "a pencil case", "a shoebox", "a first aid kit"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    "thermos": {
        "displayName": "THERMOS",
        "prompts": [
            "a thermos",
            "an insulated bottle",
            "someone holding a thermos",
            "a vacuum flask",
        ],
        "negatives": ["a water bottle", "a speaker", "a flashlight", "a can", "a vase"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    "coin": {
        "displayName": "COIN",
        "prompts": [
            "a coin",
            "coins",
            "someone holding a coin",
            "a coin in a hand",
        ],
        "negatives": ["a button", "a ring", "a bottle cap", "a washer", "a badge"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    "bottle_cap": {
        "displayName": "BOTTLE CAP",
        "prompts": [
            "a bottle cap",
            "someone holding a bottle cap",
            "a screw-on bottle cap",
            "a plastic bottle cap",
        ],
        "negatives": ["a coin", "a button", "a ring", "a coaster", "a lid"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    "deodorant": {
        "displayName": "DEODORANT",
        "prompts": [
            "a stick of deodorant",
            "deodorant",
            "someone holding deodorant",
            "a roll-on deodorant",
        ],
        "negatives": ["a glue stick", "a lipstick", "a flashlight", "a marker", "a lighter"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    "sunscreen": {
        "displayName": "SUNSCREEN",
        "prompts": [
            "a sunscreen bottle",
            "sunscreen",
            "someone holding a sunscreen tube",
            "a tube of sunscreen",
        ],
        "negatives": ["a lotion bottle", "a toothpaste tube", "a shampoo bottle", "a hand sanitizer", "a cream tube"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    "chapstick": {
        "displayName": "LIP BALM",
        "prompts": [
            "a lip balm",
            "a chapstick",
            "someone holding a lip balm tube",
            "a tube of lip balm",
        ],
        "negatives": ["a lipstick", "a lighter", "a USB drive", "a battery", "a marker cap"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    "hair_tie": {
        "displayName": "HAIR TIE",
        "prompts": [
            "a hair tie",
            "an elastic hair band",
            "someone holding a hair tie",
            "a scrunchie",
        ],
        "negatives": ["a rubber band", "a bracelet", "a ring", "a wristband", "a string"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    "cotton_swab": {
        "displayName": "COTTON SWAB / Q-TIP",
        "prompts": [
            "a cotton swab",
            "a Q-tip",
            "someone holding a cotton swab",
            "an ear cleaning stick",
        ],
        "negatives": ["a match", "a toothpick", "a straw", "a pen", "a stick"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    "bandaid": {
        "displayName": "BAND-AID",
        "prompts": [
            "a band-aid",
            "an adhesive bandage",
            "someone holding a band-aid",
            "a bandage strip",
        ],
        "negatives": ["tape", "a sticky note", "a sticker", "a patch", "a piece of paper"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    "padlock": {
        "displayName": "PADLOCK",
        "prompts": [
            "a padlock",
            "a lock",
            "someone holding a padlock",
            "a combination lock",
        ],
        "negatives": ["keys", "a watch", "a compass", "a USB drive", "a keychain"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    "glue_stick": {
        "displayName": "GLUE STICK",
        "prompts": [
            "a glue stick",
            "someone holding a glue stick",
            "a school glue stick",
            "a stick of glue",
        ],
        "negatives": ["a deodorant", "a lipstick", "a marker", "a battery", "a lighter"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    "alarm_clock": {
        "displayName": "ALARM CLOCK",
        "prompts": [
            "an alarm clock",
            "a bedside alarm clock",
            "someone holding an alarm clock",
            "a small alarm clock",
        ],
        "negatives": ["a phone", "a watch", "a clock", "a timer", "a radio"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    "plug_adapter": {
        "displayName": "POWER ADAPTER / PLUG",
        "prompts": [
            "a power adapter",
            "a wall plug",
            "someone holding a power adapter",
            "a charging adapter",
        ],
        "negatives": ["a USB drive", "a charger cable", "a power bank", "a remote", "a mouse"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    "face_mask": {
        "displayName": "FACE MASK",
        "prompts": [
            "a face mask",
            "a surgical mask",
            "someone holding a face mask",
            "a disposable face mask",
        ],
        "negatives": ["a napkin", "a tissue", "a sock", "a headband", "a bra"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    "index_card": {
        "displayName": "INDEX CARD",
        "prompts": [
            "an index card",
            "a note card",
            "someone holding an index card",
            "a blank index card",
        ],
        "negatives": ["a sticky note", "an envelope", "a playing card", "a piece of paper", "a business card"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    "clothespin": {
        "displayName": "CLOTHESPIN",
        "prompts": [
            "a clothespin",
            "a clothes peg",
            "someone holding a clothespin",
            "a wooden clothespin",
        ],
        "negatives": ["a paperclip", "a hair clip", "a chip clip", "a clamp", "a stapler"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    "magnet": {
        "displayName": "FRIDGE MAGNET",
        "prompts": [
            "a fridge magnet",
            "a refrigerator magnet",
            "someone holding a fridge magnet",
            "a magnet on a fridge",
        ],
        "negatives": ["a sticker", "a badge", "a coin", "a button", "a bottle cap"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    "mouse_pad": {
        "displayName": "MOUSE PAD",
        "prompts": [
            "a mouse pad",
            "a mousepad",
            "someone holding a mouse pad",
            "a mouse mat on a desk",
        ],
        "negatives": ["a coaster", "a cutting board", "a placemat", "a tablet", "a book"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    "hand_towel": {
        "displayName": "HAND TOWEL",
        "prompts": [
            "a hand towel",
            "a kitchen towel",
            "someone holding a dish towel",
            "a small towel",
        ],
        "negatives": ["a bath towel", "a napkin", "a rag", "a t-shirt", "a blanket"],
        "threshold": 0.22,
        "margin": 0.04,
    },
    "napkin": {
        "displayName": "NAPKIN",
        "prompts": [
            "a napkin",
            "a paper napkin",
            "someone holding a napkin",
            "a cloth napkin",
        ],
        "negatives": ["a tissue", "a towel", "a piece of paper", "a sticky note", "a handkerchief"],
        "threshold": 0.22,
        "margin": 0.04,
    },
}

# OBJECTS: dict = ORIGINAL_OBJECTS  # commented out – using filtered set below
OBJECTS: dict = {k: ORIGINAL_OBJECTS[k] for k in ["pen", "backpack", "sunglasses", "water_bottle"]}

GLOBAL_NULLS = [
    "background clutter",
    "a table surface",
    "an empty room",
    "a wall",
    "the floor",
]


def get_object(object_id: str) -> dict:
    return OBJECTS[object_id]


def get_all_ids() -> list[str]:
    return list(OBJECTS.keys())
